// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// ImageDelivery_ is an autogenerated mock type for the ImageDelivery_ type
type ImageDelivery_ struct {
	mock.Mock
}

// AddImage provides a mock function with given fields: c
func (_m *ImageDelivery_) AddImage(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ModifyImage provides a mock function with given fields: c
func (_m *ImageDelivery_) ModifyImage(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveImage provides a mock function with given fields: c
func (_m *ImageDelivery_) RemoveImage(c echo.Context) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewImageDelivery_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewImageDelivery_ creates a new instance of ImageDelivery_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewImageDelivery_(t mockConstructorTestingTNewImageDelivery_) *ImageDelivery_ {
	mock := &ImageDelivery_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
