// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	reviews "alta-airbnb-be/features/reviews"

	mock "github.com/stretchr/testify/mock"

	rooms "alta-airbnb-be/features/rooms"
)

// RoomData_ is an autogenerated mock type for the RoomData_ type
type RoomData_ struct {
	mock.Mock
}

// DeleteRoom provides a mock function with given fields: RoomEntity
func (_m *RoomData_) DeleteRoom(RoomEntity *rooms.RoomEntity) error {
	ret := _m.Called(RoomEntity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*rooms.RoomEntity) error); ok {
		r0 = rf(RoomEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertReview provides a mock function with given fields: reviewEntity
func (_m *RoomData_) InsertReview(reviewEntity *reviews.ReviewEntity) error {
	ret := _m.Called(reviewEntity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*reviews.ReviewEntity) error); ok {
		r0 = rf(reviewEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertRoom provides a mock function with given fields: roomEntity
func (_m *RoomData_) InsertRoom(roomEntity *rooms.RoomEntity) error {
	ret := _m.Called(roomEntity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*rooms.RoomEntity) error); ok {
		r0 = rf(roomEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectReviewsByRoomId provides a mock function with given fields: reviewEntity
func (_m *RoomData_) SelectReviewsByRoomId(reviewEntity *reviews.ReviewEntity) ([]*reviews.ReviewEntity, error) {
	ret := _m.Called(reviewEntity)

	var r0 []*reviews.ReviewEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*reviews.ReviewEntity) ([]*reviews.ReviewEntity, error)); ok {
		return rf(reviewEntity)
	}
	if rf, ok := ret.Get(0).(func(*reviews.ReviewEntity) []*reviews.ReviewEntity); ok {
		r0 = rf(reviewEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*reviews.ReviewEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*reviews.ReviewEntity) error); ok {
		r1 = rf(reviewEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRoomByRoomId provides a mock function with given fields: roomEntity
func (_m *RoomData_) SelectRoomByRoomId(roomEntity *rooms.RoomEntity) (*rooms.RoomEntity, error) {
	ret := _m.Called(roomEntity)

	var r0 *rooms.RoomEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*rooms.RoomEntity) (*rooms.RoomEntity, error)); ok {
		return rf(roomEntity)
	}
	if rf, ok := ret.Get(0).(func(*rooms.RoomEntity) *rooms.RoomEntity); ok {
		r0 = rf(roomEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rooms.RoomEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*rooms.RoomEntity) error); ok {
		r1 = rf(roomEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRooms provides a mock function with given fields: limit, offset, extractedQueryParams
func (_m *RoomData_) SelectRooms(limit int, offset int, extractedQueryParams map[string]interface{}) ([]*rooms.RoomEntity, error) {
	ret := _m.Called(limit, offset, extractedQueryParams)

	var r0 []*rooms.RoomEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int, map[string]interface{}) ([]*rooms.RoomEntity, error)); ok {
		return rf(limit, offset, extractedQueryParams)
	}
	if rf, ok := ret.Get(0).(func(int, int, map[string]interface{}) []*rooms.RoomEntity); ok {
		r0 = rf(limit, offset, extractedQueryParams)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rooms.RoomEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int, map[string]interface{}) error); ok {
		r1 = rf(limit, offset, extractedQueryParams)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectRoomsByUserId provides a mock function with given fields: roomEntity
func (_m *RoomData_) SelectRoomsByUserId(roomEntity *rooms.RoomEntity) ([]*rooms.RoomEntity, error) {
	ret := _m.Called(roomEntity)

	var r0 []*rooms.RoomEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(*rooms.RoomEntity) ([]*rooms.RoomEntity, error)); ok {
		return rf(roomEntity)
	}
	if rf, ok := ret.Get(0).(func(*rooms.RoomEntity) []*rooms.RoomEntity); ok {
		r0 = rf(roomEntity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*rooms.RoomEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(*rooms.RoomEntity) error); ok {
		r1 = rf(roomEntity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRoom provides a mock function with given fields: roomEntity
func (_m *RoomData_) UpdateRoom(roomEntity *rooms.RoomEntity) error {
	ret := _m.Called(roomEntity)

	var r0 error
	if rf, ok := ret.Get(0).(func(*rooms.RoomEntity) error); ok {
		r0 = rf(roomEntity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRoomData_ interface {
	mock.TestingT
	Cleanup(func())
}

// NewRoomData_ creates a new instance of RoomData_. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRoomData_(t mockConstructorTestingTNewRoomData_) *RoomData_ {
	mock := &RoomData_{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
