// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	users "alta-airbnb-be/features/users"

	mock "github.com/stretchr/testify/mock"
)

// UserData is an autogenerated mock type for the UserData_ type
type UserData struct {
	mock.Mock
}

// Delete provides a mock function with given fields: userID
func (_m *UserData) Delete(userID uint) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: input
func (_m *UserData) Insert(input users.UserEntity) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(users.UserEntity) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: email
func (_m *UserData) Login(email string) (users.UserEntity, error) {
	ret := _m.Called(email)

	var r0 users.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (users.UserEntity, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) users.UserEntity); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(users.UserEntity)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectData provides a mock function with given fields: userID
func (_m *UserData) SelectData(userID uint) (users.UserEntity, error) {
	ret := _m.Called(userID)

	var r0 users.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (users.UserEntity, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) users.UserEntity); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(users.UserEntity)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateData provides a mock function with given fields: userID, input
func (_m *UserData) UpdateData(userID uint, input users.UserEntity) error {
	ret := _m.Called(userID, input)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, users.UserEntity) error); ok {
		r0 = rf(userID, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUserData interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserData creates a new instance of UserData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserData(t mockConstructorTestingTNewUserData) *UserData {
	mock := &UserData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
