name: Deploy to GCP

on:
  push:
    branches:
      - release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/linux-pc/ALTA-Airbnb-BE
            sudo chmod 777 /var/run/docker.sock
            git pull origin main
            docker stop ${{ secrets.CONTAINER }}
            docker rm ${{ secrets.CONTAINER }}
            docker rmi ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGES }}
            docker build -t ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGES }}:latest .
            docker run -d -p 8081:8082 -e JWT_KEY=${{ secrets.JWT_KEY }} -e DBUSER=${{ secrets.DBUSER }} -e DBPASS=${{ secrets.DBPASS }} -e DBHOST=${{ secrets.DBHOST }} -e DBPORT=${{ secrets.DBPORT }} -e DBNAME=${{ secrets.DBNAME }} -e GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} --name ${{ secrets.CONTAINER }} ${{ secrets.DOCKER_USER }}/${{ secrets.IMAGES }}:latest
